name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build
      run: |
        cd Verkeerssimulatie
        mkdir build
        cd build
        cmake  ..
        make
    - name: Test
      run: |
        cd Verkeerssimulatie
        cd workingDirectory
        ../build/Verkeerssimulatie.test
      
